apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kro
  namespace: argocd
  labels:
    env: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: kro
    repoURL: https://api.github.com/repos/kro-run/kro/releases/latest
    helm:
      valueFiles:
        releaseName: kro
    chart: kro
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kro
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true